repos:
    - repo: local
      hooks:
          - id: copyright
            name: Check copyright notices
            language: system
            entry: python3 tools/check_copyright_notice.py
            pass_filenames: false
            stages: [pre-commit]
          - id: rustfmt
            name: Run `rustfmt`
            language: rust
            types: [rust]
            entry: cargo +nightly-2026-01-01 fmt --check
            pass_filenames: false
            stages: [pre-commit]
          - id: clippy
            name: Run cargo clippy
            types: [rust]
            language: rust
            entry: cargo clippy --workspace --all-targets -- -D warnings
            pass_filenames: false
            stages: [pre-push]
    - repo: https://github.com/crate-ci/typos
      rev: v1.32.0
      hooks:
          - id: typos
